### ISSUE TITLE
Windows 3rd party CD burning

### ISSUE THREAD

**Issue by KirgoPlayer** [arduinocelentano/cdimage#10]
What other Windows applications other than cdrecord can burn the tracks made by CDimage on CD's?

**Comment by rwilson504** [comment]
I was able to get cdrecord to work in windows.  I download the **portable version** of [InfraRecorder](http://infrarecorder.org/) for Windows, it includes a windows version of cdrtools that could see the drive.  From there I used the command line to run the cdrecord command and the track did burn.  

![image](https://user-images.githubusercontent.com/7444929/180474794-64bac334-42f4-4fc2-95ff-8b7c5ef77dea.png)

That being said the cd didn't end up looking anything like the image I had used it just had a bunch of lines around the disk that made it look like ripples of water after a rock was thrown in.

**Comment by KirgoPlayer** [comment]
> I was able to get cdrecord to work in windows.  I download the **portable version** of [InfraRecorder](http://infrarecorder.org/) for Windows, it includes a windows version of cdrtools that could see the drive.  From there I used the command line to run the cdrecord command and the track did burn.  
> 
> ![image](https://user-images.githubusercontent.com/7444929/180474794-64bac334-42f4-4fc2-95ff-8b7c5ef77dea.png)
> 
> That being said the cd didn't end up looking anything like the image I had used it just had a bunch of lines around the disk that made it look like ripples of water after a rock was thrown in.

Hi! Thanks for the answer.I have 2 questions:

1. Can you send me a photo of the CD you burned?

2.Do you think that the distorsion of the image appeared because of the software or because the wrong geometry?
