### ISSUE TITLE
Reburn CD-RW's?

### ISSUE THREAD

**Issue by KirgoPlayer** [arduinocelentano/cdimage#11]
If I blank a CD-RW that was burned an image on using this method can I delete the first one and reburn another image on it again?

**Comment by rwilson504** [comment]
If doing this in Windows I found that InfraRecorder worked to completely wipe the disk.  The built in Erase for Windows 10+ did not work.

Settings for InfraRecorder
![image](https://user-images.githubusercontent.com/7444929/183265260-f501f7dd-ca7d-4bad-a40e-26fe6423dbce.png)

**Comment by KirgoPlayer** [comment]
> If doing this in Windows I found that InfraRecorder worked to completely wipe the disk.  The built in Erase for Windows 10+ did not work.
> 
> Settings for InfraRecorder
> ![image](https://user-images.githubusercontent.com/7444929/183265260-f501f7dd-ca7d-4bad-a40e-26fe6423dbce.png)
> 

Thanks for the help! I will try it right away! Does it work with the portable version of InfraRecorder?

**Comment by rwilson504** [comment]
Yes the portable version is the one I'm using.

All this work just to make some fun gifts for my friend :)
